### ISSUE TITLE
tar: Error opening archive: Unrecognized archive format

### ISSUE THREAD

**Issue by dpo** [ararslan/CirrusCI.jl#15] opened 2022-09-09 20:30 UTC
Recently, FreeBSD CI jobs have been failing at the install step with
```
sh -c "$(fetch https://raw.githubusercontent.com/ararslan/CirrusCI.jl/master/bin/install.sh -o -)"
-                                                     5031  B   94 MBps    00s
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
Updating database digests format: . done
The following 5 package(s) will be affected (of 0 checked):
New packages to be INSTALLED:
	libidn2: 2.3.2
	libpsl: 0.21.1_4
	libssh2: 1.10.0,3
	libunistring: 1.0
Installed packages to be UPGRADED:
	curl: 7.74.0 -> 7.85.0
Number of packages to be installed: 4
Number of packages to be upgraded: 1
The process will require 5 MiB more space.
2 MiB to be downloaded.
[1/5] Fetching libidn2-2.3.2.pkg: .......... done
[2/5] Fetching libunistring-1.0.pkg: .......... done
[3/5] Fetching libssh2-1.10.0,3.pkg: .......... done
[4/5] Fetching libpsl-0.21.1_4.pkg: ........ done
[5/5] Fetching curl-7.85.0.pkg: .......... done
Checking integrity... done (0 conflicting)
[1/5] Installing libunistring-1.0...
[1/5] Extracting libunistring-1.0: .......... done
[2/5] Installing libidn2-2.3.2...
[2/5] Extracting libidn2-2.3.2: .......... done
[3/5] Installing libssh2-1.10.0,3...
[3/5] Extracting libssh2-1.10.0,3: .......... done
[4/5] Installing libpsl-0.21.1_4...
[4/5] Extracting libpsl-0.21.1_4: .......... done
[5/5] Upgrading curl from 7.74.0 to 7.85.0...
[5/5] Extracting curl-7.85.0: .......... done
tar: Error opening archive: Unrecognized archive format
```
Is it something with the `install` script or something with CirrusCI?

The failure occurs with FreeBSD 12.1 and 13.

Example: https://cirrus-ci.com/task/5487976753922048?logs=install

Thanks!

**Comment by ararslan** [comment] 2022-09-09 21:26
...weird. Seems also mildly sus that curl is being _upgraded_ since I was under the impression it was not installed by default on the base images. So, I don't know whether this will help but can you try adding the following to the `install_script` in your YAML file _before_ the `sh -c "$(fetch ...)"` bit?
```
export ASSUME_ALWAYS_YES=yes
pkg clean -y
pkg bootstrap -f
pkg update
pkg upgrade -y
```
I wonder if there's some state being cached that needs a reset. Not sure what the best way to actually do that is, but the above tries to basically clean up and reinstall the package manager.

**Comment by dpo** [comment] 2022-09-09 22:13
Thanks for the quick reply! The result is the same: https://cirrus-ci.com/task/4808757715664896

Is the error occuring in `install.sh`?

**Comment by ararslan** [comment] 2022-09-09 22:54
It's coming from somewhere in there but unfortunately the amount of logging that script does is minimal at best. Given that the error appears to occur immediately after the extraction of curl I assumed it was an issue with the archive that the package manager was fetching but that seems not to be the case since you get the error even when the `pkg install curl` that `install.sh` does internally is a no-op. The only other tarball it could be failing on then would be Julia, but `curl`ing `julia-1.8-latest-freebsd-x86_64.tar.gz` works fine for me locally on FreeBSD. 😕 I did a `curl -X PURGE` on the URL the script downloads to try to forcibly clear the Fastly cache for Julia's binaries. Maybe that will help?

**Comment by dpo** [comment] 2022-09-10 17:16
So the error is that `curl` fails to fetch the Julia archive and fetches instead the error message
```
<?xml version='1.0' encoding='UTF-8'?><Error><Code>UserProjectAccountProblem</Code><Message>The project to be billed is associated with a delinquent billing account.</Message><Details>The billing account for the owning project is disabled in state delinquent</Details></Error>
```
https://cirrus-ci.com/task/5196056349638656?logs=install#L203

**Comment by ararslan** [comment] 2022-09-10 17:57
Uh, wtaf. I can't reproduce that locally:
```
$ curl -LO https://julialang-s3.julialang.org/bin/freebsd/x64/1.8/julia-1.8-latest-freebsd-x86_64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  121M  100  121M    0     0  38.6M      0  0:00:03  0:00:03 --:--:-- 38.8M
$ file julia-1.8-latest-freebsd-x86_64.tar.gz
julia-1.8-latest-freebsd-x86_64.tar.gz: gzip compressed data, last modified: Tue Sep  6 19:42:16 2022, from Unix, original size modulo 2^32 466492416
```
I have literally zero idea why this could be happening.

**Comment by dpo** [comment] 2022-09-10 18:08
I can't reproduce it locally either. But can you reproduce it on CirrusCI?

**Comment by ararslan** [comment] 2022-09-10 18:21
Yes, e.g. in #13.

I looked into this some more and spoke with some folks in the Julia Slack. That error comes from Google Cloud Platform, and notably Cirrus' FreeBSD builds run on that service. As it turns out, fetching Julia things from the official servers will actually redirect to a GCP mirror when running on GCP, and the Julia Project recently made some kind of changes to the GCP account billing. Sounds like there's an issue with those updates and in the meantime, the GCP redirect has now been disabled, which should fix the issue.

**Comment by ararslan** [comment] 2022-09-10 18:31
Awesome, seems to be working now so I'll close this. Thanks so much for the report and for your help debugging, that was instrumental to getting this figured out. Let me know if you run into any more issues!

**Closed as completed by ararslan** 2022-09-10 18:31 UTC

**Comment by ararslan** [comment] 2022-09-10 19:33
The redirect is apparently still in place for nightlies so the error reported here isn't completely gone but that should be fixed soon. They live in a different S3 bucket than everything else.
